### ISSUE TITLE
Commentaire du projet

### ISSUE THREAD

**Issue by Patouvoodo** [Paul234Code/BDApplication#5]
Commentaires:

Ligne 78 : while (true)
Utilisez plutôt une variable et utilisez une condition indirectement true ou false. Exemple: while (z < 5)

Ligne 98: var nomAnimal
Pensez à utiliser des variables typés (string, bool, int). Le type var possède des limites, assures-toi de comprendre les limites du var

Ligne 288: couleur == "bleu" || couleur == "rouge" || couleur == "violet";
Il faut utiliser des comparaisons avec string compare et non des equals.

Il faut également penser à découper/aérer le code davantage. Le code est souvent pris dans un pain et il aurait été facile de découper en plus petites fonctions. Il faut penser découpage!

En dehors de ça c'est un excellent travail! Bravo et bonne continuité.

**Comment by Paul234Code** [comment]
> Commentaires:
> 
> Ligne 78 : while (true) Utilisez plutôt une variable et utilisez une condition indirectement true ou false. Exemple: while (z < 5)
> 
> Ligne 98: var nomAnimal Pensez à utiliser des variables typés (string, bool, int). Le type var possède des limites, assures-toi de comprendre les limites du var
> 
> Ligne 288: couleur == "bleu" || couleur == "rouge" || couleur == "violet"; Il faut utiliser des comparaisons avec string compare et non des equals.
> 
> Il faut également penser à découper/aérer le code davantage. Le code est souvent pris dans un pain et il aurait été facile de découper en plus petites fonctions. Il faut penser découpage!
> 
> En dehors de ça c'est un excellent travail! Bravo et bonne continuité.

Merci Patrick pour le feedback je viens de faire le decoupage et les corrections
